<a href="https://colab.research.google.com/github/ShasHero006/Python/blob/main/NumPy_Assignment_(Practical_Questions).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Practical Questions**

# **Q.1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**
Ans.

In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

# Interchange rows and columns
interchanged_array = array.transpose()

print("\nArray with interchanged rows and columns:")
print(interchanged_array)

Original array:
[[15 46 83]
 [48 98 32]
 [35 34 40]]

Array with interchanged rows and columns:
[[15 48 35]
 [46 98 34]
 [83 32 40]]


__________________________________________________________________________

# **Q. 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**
Ans.

In [ ]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("\nReshaped 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


___________________________________________________________________________

# **Q.3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**
Ans.

In [ ]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.rand(4, 4)

print("Original array:")
print(array)

# Add a border of zeros around it
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("\nArray with a border of zeros:")
print(bordered_array)

Original array:
[[0.41170245 0.02554012 0.19745167 0.45223336]
 [0.9272731  0.78925469 0.39940432 0.66525632]
 [0.17922039 0.90573281 0.89125812 0.74130862]
 [0.27066061 0.51185594 0.10818506 0.97489697]]

Array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.41170245 0.02554012 0.19745167 0.45223336 0.        ]
 [0.         0.9272731  0.78925469 0.39940432 0.66525632 0.        ]
 [0.         0.17922039 0.90573281 0.89125812 0.74130862 0.        ]
 [0.         0.27066061 0.51185594 0.10818506 0.97489697 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


__________________________________________________________________________

# **Q.4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**
Ans.

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


__________________________________________________________________________

# **Q.5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**
Ans.

In [ ]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

print("Original array:")
print(array)

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)
swapcase_array = np.char.swapcase(array)

print("\nUppercase array:")
print(uppercase_array)

print("\nLowercase array:")
print(lowercase_array)

print("\nTitlecase array:")
print(titlecase_array)

print("\nCapitalize array:")
print(capitalize_array)

print("\nSwapcase array:")
print(swapcase_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Capitalize array:
['Python' 'Numpy' 'Pandas']

Swapcase array:
['PYTHON' 'NUMPY' 'PANDAS']


___________________________________________________________________________

# **Q.6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**
Ans.

In [ ]:
import numpy as np

# Generate a NumPy array of words
words = np.array(['apple', 'banana', 'cherry'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original array:")
print(words)

print("\nArray with spaces between characters:")
print(spaced_words)

Original array:
['apple' 'banana' 'cherry']

Array with spaces between characters:
['a p p l e' 'b a n a n a' 'c h e r r y']


__________________________________________________________________________

# **Q.7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**
Ans.

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Element-wise addition
addition_result = np.add(array1, array2)
print("\nElement-wise addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = np.subtract(array1, array2)
print("\nElement-wise subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = np.multiply(array1, array2)
print("\nElement-wise multiplication:")
print(multiplication_result)

# Element-wise division
division_result = np.divide(array1, array2)
print("\nElement-wise division:")
print(division_result)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


___________________________________________________________________________

# **Q.8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**
Ans.

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal elements:")
print(diagonal_elements)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


___________________________________________________________________________

# **Q.9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array**
Ans.

In [ ]:
import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)

print("Original array:")
print(array)

# Find and display all prime numbers in the array
prime_numbers = [num for num in array if is_prime(num)]

print("\nPrime numbers in the array:")
print(prime_numbers)


Original array:
[270 705 146 458 495 613 753 757 597 518 256 788  57 424 613  37 845 112
 674 429 581 275 889 947 339 198 216 209 799 217 768  75 838 881 211 967
 179 627 252 797 323 273 678 389 808 982 348 989 784 217 608 461 879 211
 546 800 115  32 227 727 126 135 607 229  30 787  59 646 487 538 781 210
  59 659 865   4 624 730 510 748 614  91  20 854 296 150 466 828 947 907
 541  38 716 249 498 836 742 331 943 765]

Prime numbers in the array:
[613, 757, 613, 37, 947, 881, 211, 967, 179, 797, 389, 461, 211, 227, 727, 607, 229, 787, 59, 487, 59, 659, 947, 907, 541, 331]


__________________________________________________________________________

# **Q.10. . Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**
Ans.

In [ ]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
temperatures = np.random.randint(15, 35, size=30)

print("Daily temperatures:")
print(temperatures)

# Calculate weekly averages
weekly_averages = []
for i in range(0, len(temperatures), 7):
  week_temps = temperatures[i:i+7]
  if len(week_temps) > 0:
    weekly_average = np.mean(week_temps)
    weekly_averages.append(weekly_average)

print("\nWeekly average temperatures:")
print(weekly_averages)


Daily temperatures:
[17 21 19 17 19 30 33 33 26 17 33 33 29 32 31 16 24 24 31 29 20 18 34 18
 28 22 27 24 33 25]

Weekly average temperatures:
[22.285714285714285, 29.0, 25.0, 24.428571428571427, 29.0]


___________________________________________________________________________